name: Release Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set version from git tag
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          npm version $VERSION --no-git-tag-version --prefix packages/core
          npm version $VERSION --no-git-tag-version --prefix packages/app
          npm version $VERSION --no-git-tag-version

      - name: Build and Publish App
        run: pnpm package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-website:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Notify Website Repo
        run: |
          curl -X POST https://api.github.com/repos/MickaelRiss/kyte_website/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
          -d '{"event_type": "new_release", "client_payload": { "version": "${{ github.ref_name }}" }}'
